name: app_for_softevol
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  device_preview: 1.0.0
#  google_fonts: ^2.1.0
#  meta: ^1.7.0
  json_annotation: ^4.3.0
  flutter_svg: 0.23.0+1
  flutter_icons: ^1.1.0
  flutter_hooks: ^0.18.1
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # To run use 'flutter pub run build_runner build' command
  build_runner: ^2.1.5
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  flutter_gen: ^4.1.2
  flutter_gen_runner: ^4.1.2
  flutter_lints: ^1.0.4

# After adding assets run 'flutter pub run build_runner build'
flutter_gen:
  output: lib/utils/values/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true

# After adding assets run 'flutter pub run build_runner build'
flutter:
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/icons/discover.svg
    - assets/images/icons/hot.svg
    - assets/images/icons/inbox.svg
    - assets/images/icons/watch.svg
    - assets/images/icons/play.svg
    - assets/images/icons/eye.svg
    - assets/images/icons/discord.svg
    - assets/images/fgc_rumble.png
    - assets/images/profile.png
    - assets/images/smash_stockpile.png
    - assets/images/valorant_volume.png
    - assets/images/gifs/verification.gif


  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/fonts/aktiv_grotesk/AktivGroteskCorp-Regular.ttf
        - asset: assets/fonts/aktiv_grotesk/AktivGroteskCorp-Bold.ttf
          weight: 600

